---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nebo-k8s
  region: us-east-1
  version: "1.26"
availabilityZones:
- us-east-1a
- us-east-1b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.small
  minSize: 1
  maxSize: 3
  desiredCapacity: 1
  volumeSize: 20