---
kind: ConfigMap
apiVersion: v1
metadata:
  name: openresty
data:
  index.html: |
    <html>
    <head>
        <title>Test page</title>
        <meta charset="UTF-8">
    </head>
    <body>
      <h1>Тестова сторінка</h1>

      <p>перевіряємо дані з  hashicorp vault:</p>
      <p>Пароль: <b>$DB_PASSWORD</b> </p>

    </body>
    </html>