apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-application
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "db_user"
        secretPath: "secret/data/test-pass"
        secretKey: "db_user"
      - objectName: "db_password"
        secretPath: "secret/data/test-pass"
        secretKey: "db_password"
      - objectName: "db_endpoint"
        secretPath: "secret/data/test-pass"
        secretKey: "db_endpoint"